author: Yevhenii Bykov
show_downloads: true
title: Keycloak Compose
description: Example how to run Keycloak 17.0.0 using Docker Compose and PostgreSQL
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
