services:
  postgres:
    image: "postgres:13.5-alpine"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      PGPASSWORD: password
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  keycloak:
    image: "quay.io/keycloak/keycloak:17.0.0"
    restart: unless-stopped
    command: ["start-dev", "--http-relative-path", "/auth"]
    depends_on:
      - postgres
    environment:
      - KC_DB=postgres
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_METRICS_ENABLED=true
      - KC_FEATURES=preview,account2,admin2,docker
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 8080:8080

