---
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: system
    static_configs:
      - targets: ['prometheus:9090']

rule_files:
  - 'prometheus-rules.yml'

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093
